### ISSUE TITLE
removing @import rules when missing semicolon ;

### ISSUE THREAD

**Issue by dotnetCarpenter** [postcss/postcss-custom-media#14]
Tested with `postcss` version 5.0.9 and `postcss-custom-media` version 5.0.0.

Run `postcss --use postcss-custom-media`

Test case:

``` css
@custom-media --viewport-mobile (max-width: 640px)
/* =fonts */
@import url(https://fonts.googleapis.com/css?family=Roboto:400,700,300,300italic);

* {
  font-family: "Roboto";
}
```

Output:

``` css
* {
  font-family: "Roboto";
}
```
