### ISSUE TITLE
Improper circular rule detection

### ISSUE THREAD

**Issue by mikestopcontinues** [postcss/postcss-custom-media#18]
Running up to date versions of everything, the following throws an error...

```css
:root {
  --grid-mobile-width: 320px;
}

@custom-media --cell screen and (width < var(--grid-mobile-width));

@media (--cell) {}
```

> ⚠  Circular @custom-media definition for '--cell'. The entire rule has been removed from the output. [postcss-custom-media]

All relevant plugins are bundled in `cssnext`.
