### ISSUE TITLE
Importing file with :root declarations 

### ISSUE THREAD

**Issue by QuantumInformation** [postcss/postcss-custom-media#25]
I take it using it like this is not supported, which was my 1st attempt?

@import "css-variables/breakpoints/generic.pcss";

generic:
```css
:root {
  --small: 480px;
  --medium: 768px;
  --large: 992px;
  --xlarge: 1200px;
}
```

usage:

![image](https://cloud.githubusercontent.com/assets/216566/21925752/b3252132-d976-11e6-8e3a-bbbb476efae1.png)
