### ISSUE TITLE
Help understanding changes from v6 to v7

### ISSUE THREAD

**Issue by emmenko** [postcss/postcss-custom-media#47]
Hi, it's me again 😅

Today my team and I found out a problem with `v7` which we recently updated to. I tried finding out the cause, but somehow upgrading from `6.0.0` to `7.x.x` breaks the transformations. There is no error during compilation but the media queries are not being transformed.

I'll explain a bit our setup, but my question would be if we need to configure something specific on our side or if there is a problem with the plugin.

You can see it below:

![image](https://user-images.githubusercontent.com/1110551/46807612-a0a20400-cd6a-11e8-8719-77da25c303a9.png)

![image 1](https://user-images.githubusercontent.com/1110551/46807668-c9c29480-cd6a-11e8-944c-4dbb9ef23c8b.png)

Our postcss config is as following:

```js
{
  loader: require.resolve('postcss-loader'),
  options: {
    ident: 'postcss',
    plugins: () => [
      postcssImport({ path: sourceFolders }),
      postcssPresetEnv({
        browsers: browserslist.development,
        autoprefixer: { grid: true },
      }),
      postcssCustomMediaQueries(),
      postcssCustomProperties({ preserve: false }),
      postcssColorModFunction(),
      postcssReporter(),
    ],
  },
},
```

An example of css module file that uses this is:

```css
/* col.mod.css */
@import '@commercetools-frontend/ui-kit/materials/spacings.mod.css';
@import '@commercetools-frontend/ui-kit/materials/media-queries.mod.css';

:root {
  /* ... */
  --col-12-width: calc(100% / (12 / 12));
}

@media (--screen-min-mobile) and (--screen-max-desktop), (--screen-max-mobile) {
  /* ... */
  .col-xsm-12 {
    width: var(--col-12-width);
    padding: 0 0 var(--spacing-16);
  }
}
```

where `--screen-` come from `media-queries.mod.css`

```css
/* media-queries.mod.css */

:root {
  /* MAX-WIDTH */
  @custom-media --screen-max-mobile (width < 768px); /* xsm */
  @custom-media --screen-max-desktop (width < 1024px); /* sm */
  @custom-media --screen-max-biggerdesktop (width < 1280px); /* md */
  @custom-media --screen-max-giantdesktop (width < 1680px); /* lg */
  @custom-media --screen-max-jumbodesktop (width < 1920px); /* xlg */

  /* MIN-WIDTH */
  @custom-media --screen-min-mobile (width >= 768px); /* xsm */
  @custom-media --screen-min-desktop (width >= 1024px); /* sm */
  @custom-media --screen-min-biggerdesktop (width >= 1280px); /* md */
  @custom-media --screen-min-giantdesktop (width >= 1680px); /* lg */
  @custom-media --screen-min-jumbodesktop (width >= 1920px); /* xlg */
}
```

This works fine with `v6.0.0` but with `v7.x.x` stops working.

Any idea what is going on here? Any help would be much appreciated, thanks! 🙏
