### ISSUE TITLE
simple-vars not resolved

### ISSUE THREAD

**Issue by VinSpee** [postcss/postcss-custom-media#7]
## Actual
When using a custom property (as outlined in [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties), my custom property is not resolved inside a custom media definition.

### INPUT:
```css
:root {
  --ms6: 4.5em;
}

@custom-media --palm (min-width: var(--ms6));

@media (--palm) {
  html {
    color: red !important;
  }
}

```

### OUTPUT:
```css
@media min-width: var(--ms6) {
  html {
    color: red;
  }
}
```

## Expected
My custom property should be resolved.
### INPUT:
```css
:root {
  --ms6: 4.5em;
}

@custom-media --palm (min-width: var(--ms6));

@media (--palm) {
  html {
    color: red !important;
  }
}

```

### OUTPUT:
```css
@media (min-width: 4.5em)  {
  html {
    color: red;
  }
}
```

## Reproduction
1. set up build (something like this):
  ```js
    return gulp.src(paths.source.client.main_style)
    .pipe(postcss([
      inline({
        path: ['./app/styles/']
      }),
      customProperties(),
      customMedia()
    ]))
    .pipe(gulp.dest(paths.dest.client.styles))

  ```
1. add a custom property
2. use it in an `@custom-media` definition
3. see that your output contains the custom property name, not the rendered value.

Am I doing anything wrong?

Thanks!

**Comment by MoOx** [comment]
According to specs you cannot do that. Media queries are different than properties values that can changes with cascade. @tabatkins gave me a pretty good explanation once, cannot remember completely nor find it :/

**Comment by tabatkins** [comment]
Right.  "Variables" are just custom properties.  Properties apply to elements, and the `var()` function takes the value of the corresponding property on the element and substitutes it in.

`@media` isn't an element, and so doesn't have any property to take from.

**Comment by VinSpee** [comment]
interesting and understood. Any thoughts on ways to manage custom media values? I'm using a [modular scale](https://github.com/VinSpee/css-modularscale) for sizing, and it essentially gives a list of sizes in `em`. Do I really have to manually put in the value? Feels archaic :-)

**Comment by VinSpee** [comment]
Looks like I could use something like [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) to do the trick. Thanks and sorry for the false alarm!

**Comment by tabatkins** [comment]
Note as well that the CSSWG is developing custom media queries <http://dev.w3.org/csswg/mediaqueries/#custom-mq> which'll help you out natively.

**Comment by VinSpee** [comment]
@tabatkins not really - as far as I understand it, I will have to supply the actual value to the custom media query when I'm creating it, so I couldn't do something like:

```css
:root {
  --ms6: 4.5em;
}

@custom-media --palm (min-width: var(--ms6));

@media (--palm) {
  html {
    color: red !important;
  }
}
```

**Comment by tabatkins** [comment]
Yes, you have to put the value into the MQ.  If you're using the value in both Variables and MQs, you'll have to repeat it.  CSS is unlikely to sprout macros that allow you to substitute values into arbitrary contexts.

**Comment by VinSpee** [comment]
@MoOx looks like it doesn't even work with postcss-simple-vars:

### INPUT:
```css
@custom-media --palm (min-width: $palm);
@media (--palm) {
    html {
         background: red !important;
    }
  }

```

### OUTPUT:
```css
@media (min-width: $palm) {
    html {
         background: red !important;
    }
  }
```
