### ISSUE TITLE
postcss-custom-media + postcss-mixins

### ISSUE THREAD

**Issue by spacedawwwg** [postcss/postcss-custom-media#78]
I don't know if this is postcss-custom-media or postcss-mixins but I'm not able to get postcss-custom-media to work on CSS generated by postcss-mixins.

``` CSS
.l-grid {
  display: grid;
  gap: var(--grid-gap);
}

/**
* Grid modifiers. Will generate us a suite of classes like:
*
*  .l-grid--2 {} // 2 columns
*  .l-grid--3 {} // 3 columns
*  .l-grid--4 {} // 4 columns etc.
*
* The same classes from above will also be prefixed with a breakpoint value:
*
*  .sm:l-grid--2 {}
*  .md:l-grid--2 {}
*  .lg:l-grid--2 {} // etc.
*
*  .etc
*/
@mixin gridColumns 12, l-grid;
```

This is my config. + mixin.

```JS
const postcssImport = require('postcss-import');
const postcssARulesVariables = require('postcss-at-rules-variables');
const postcssMixins = require('postcss-mixins');
const postcssNested = require('postcss-nested');
const postcssCustomMedia = require('postcss-custom-media');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const breakpoints = require('../packages/core/tokens/dist/tokens.json').breakpoint;

function gridColumnItem(bp, column, prefix) {
  const baseCss = `
    .${prefix}--${column} {
      grid-template-columns: repeat(${column}, 1fr);
    }
  `;

  const breakpointsCss = Object.keys(bp).map(
    key => /* css */ `
      @media (--screen-${key}-min) {
        .${key}\\:${prefix}--${column} {
          grid-template-columns: repeat(${column}, 1fr);
        }
      }
    `
  );

  return [baseCss, ...breakpointsCss].join(' ');
}

function gridColumns(mixin, columns = 12, prefix = 'uol-l-grid') {
  let gridCss = '';
  let column = 0;

  while (column < columns) {
    gridCss += gridColumnItem(breakpoints, column + 1, prefix);
    column += 1;
  }

  mixin.replaceWith(gridCss);
}

const plugins = [
  postcssImport,
  postcssARulesVariables,
  postcssMixins({
    mixins: {
      gridColumns,
    },
  }),
  postcssNested,
  postcssCustomMedia,
  autoprefixer,
  cssnano({
    preset: [
      'default',
      {
        colormin: false,
      },
    ],
  }),
];

module.exports = {
  plugins,
};
```
Unfortunately it does not process the custom media and the end ouput is like so:

@media (--screen-xl-min){
  .xl\:l-grid--12{
    grid-template-columns:repeat(12,1fr)
  }
}
